CREATE ROLE admin1 WITH LOGIN SUPERUSER CREATEDB CREATEROLE PASSWORD '280102';
CREATE ROLE admin2 WITH LOGIN SUPERUSER CREATEDB CREATEROLE PASSWORD '280102';
CREATE ROLE admin1 WITH LOGIN SUPERUSER CREATEDB CREATEROLE PASSWORD '280102';
CREATE DATABASE admin1_data OWNER admin1;
GRAND ALL PRIVILEGES ON DATABASE admin1_data TO admin1;
CREATE DATABASE admin2_data OWNER admin2;
GRAND ALL PRIVILEGES ON DATABASE admin2_data TO admin2;
