- name: Install necesscery packages
  apt:
    name:
      - gnupg2
      - wget
      - vim

- name: Creating an empty file
  file:
    path: "/etc/apt/sources.list.d/pgdg.list"
    state: touch

- name: Add the repository that provides PostgreSQL 14 on Ubuntu
  lineinfile:
    path: "/etc/apt/sources.list.d/pgdg.list"
    line: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
    insertbefore: BOF

- name: Import the GPG signing key for the repository
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Re-update vm
  apt:
    update_cache: yes

- name: Install postgresSQL
  apt:
    name: "{{ postgres_package }}"

- name: Install essential package for postgresql
  package:
    name: python3-psycopg2
    state: present

- name: Create db user admin1
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    state: present
    name: admin1
    password: 280102

- name: Provide permission
  become: true
  become_user: postgres
  postgresql_user:
    name: admin1
    role_attr_flags: SUPERUSER,CREATEDB

- name: Create admin1's database
  become: true
  become_user: postgres
  postgresql_db:
    name: admin1_db
    state: present
    owner: admin1

- name: Create db user admin2
  community.postgresql.postgresql_user:
    state: present
    name: admin2
    password: 280102
  become: true
  become_user: postgres

- name: Provide permission
  become: true
  become_user: postgres
  postgresql_user:
    name: admin2
    role_attr_flags: SUPERUSER,CREATEDB

- name: Create admin2's database
  become: true
  become_user: postgres
  postgresql_db:
    name: admin2_db
    state: present
    owner: admin2




